import { Image } from 'expo-image';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowLeft, Share2 } from 'lucide-react-native';
import { useState } from 'react';
import { Alert, Share, StyleSheet, View } from 'react-native';
import { EmptyState, ErrorState, LoadingState } from '@/components/feedback';
import { AppText, Button, Card, IconButton, Screen, StatusChip } from '@/components/ui';
import { publicAppConfig } from '@/config/public'; import { colors } from '@/design/colors'; import { radii } from '@/design/radii'; import { spacing } from '@/design/spacing'; import { RoomImage } from '@/features/rooms/components/RoomImage'; import { useRoom } from '@/features/rooms/hooks/useRooms'; import { BOOKING_UNAVAILABLE_MESSAGE } from '@/features/rooms/utils/bookingScope'; import { roomStatusLabels, roomStatusTones } from '@/features/rooms/utils/status'; import { usePublicProperty } from '@/features/properties/hooks/useProperty'; import { formatCurrency } from '@/utils/format';

export default function PublicRoomDetail() {
  const { roomId } = useLocalSearchParams<{ roomId: string }>(); const router = useRouter(); const query = useRoom(publicAppConfig.propertyId, roomId, 'public'); const property = usePublicProperty(publicAppConfig.propertyId); const [selected, setSelected] = useState<string | undefined>();
  if (query.isLoading) return <Screen><LoadingState /></Screen>; if (query.error) return <Screen><ErrorState description="Detail kamar belum dapat dimuat." onRetry={() => void query.refetch()} /></Screen>; if (!query.data) return <Screen><EmptyState title="Kamar tidak tersedia" description="Kamar tidak ditemukan, belum dipublikasikan, atau telah diarsipkan." /></Screen>;
  const room = query.data; const hero = selected ?? room.coverImageUrl ?? room.imageUrls[0];
  return <><Stack.Screen options={{ title: room.name }} /><Screen contentStyle={styles.screen}><View style={styles.hero}><RoomImage uri={hero} label={`Foto ${room.name}`} style={styles.heroImage} /><View style={styles.heroActions}><IconButton accessibilityLabel="Kembali" icon={<ArrowLeft color={colors.neutral[800]} />} onPress={() => router.back()} /><IconButton accessibilityLabel="Bagikan kamar" icon={<Share2 color={colors.neutral[800]} />} onPress={() => void Share.share({ message: `${room.name} - ${formatCurrency(room.monthlyPrice)}/bulan` })} /></View></View><View style={styles.title}><StatusChip label={roomStatusLabels[room.status]} tone={roomStatusTones[room.status]} /><AppText variant="titleXl">{room.name}</AppText><AppText tone="secondary">{property.data?.locationLabel ?? 'Manzsa Residence'}</AppText></View><Card><View style={styles.meta}><View><AppText variant="caption" tone="muted">UKURAN</AppText><AppText variant="titleSm">{room.size ?? 'Belum diisi'}</AppText></View><View><AppText variant="caption" tone="muted">KAPASITAS</AppText><AppText variant="titleSm">{room.capacity} orang</AppText></View><View><AppText variant="caption" tone="muted">KODE</AppText><AppText variant="titleSm">{room.code}</AppText></View></View></Card>{room.imageUrls.length ? <View style={styles.thumbs}>{room.imageUrls.map((uri, index) => <Image key={uri} source={{ uri }} accessibilityLabel={`Pilih foto ${index + 1}`} alt={`Foto ${room.name} ${index + 1}`} contentFit="cover" cachePolicy="memory-disk" style={[styles.thumb, hero === uri && styles.thumbActive]} onTouchEnd={() => setSelected(uri)} />)}</View> : null}<View style={styles.section}><AppText variant="titleLg">Fasilitas kamar</AppText><View style={styles.facilities}>{room.facilities.map((item) => <Card key={item} padding={3}><AppText variant="bodySm">{item}</AppText></Card>)}</View></View><View style={styles.section}><AppText variant="titleLg">Detail kamar</AppText><Card><AppText tone="secondary">{room.description}</AppText>{room.depositAmount != null ? <AppText>Deposit {formatCurrency(room.depositAmount)}</AppText> : null}{room.minimumRentalMonths ? <AppText>Minimum sewa {room.minimumRentalMonths} bulan</AppText> : null}</Card></View><View style={styles.price}><View><AppText variant="caption" tone="muted">Harga sewa</AppText><AppText variant="moneyMd">{formatCurrency(room.monthlyPrice)}<AppText variant="caption" tone="muted">/bulan</AppText></AppText></View><Button label="Ajukan booking" disabled={room.status !== 'available'} onPress={() => Alert.alert('Booking segera tersedia', BOOKING_UNAVAILABLE_MESSAGE)} /></View></Screen></>;
}
const styles = StyleSheet.create({ screen: { maxWidth: 900, paddingBottom: 120 }, hero: { position: 'relative', overflow: 'hidden', borderRadius: radii.xl }, heroImage: { height: 335, aspectRatio: undefined }, heroActions: { position: 'absolute', left: spacing[4], right: spacing[4], top: spacing[4], flexDirection: 'row', justifyContent: 'space-between' }, title: { gap: spacing[2] }, meta: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing[4] }, thumbs: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] }, thumb: { width: 64, height: 64, borderRadius: radii.sm, borderWidth: 2, borderColor: 'transparent' }, thumbActive: { borderColor: colors.brand[500] }, section: { gap: spacing[3] }, facilities: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] }, price: { position: 'relative', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing[4], padding: spacing[4], borderRadius: radii.xl, backgroundColor: colors.neutral[0], borderWidth: 1, borderColor: colors.neutral[100] } });
