import { useMemo, useState } from 'react';
import { RefreshControl, StyleSheet, useWindowDimensions, View } from 'react-native';
import { EmptyState, ErrorState, LoadingState, OfflineBanner } from '@/components/feedback';
import { AppText, Button, Card, Screen, TextField } from '@/components/ui';
import { publicAppConfig } from '@/config/public'; import { spacing } from '@/design/spacing'; import { PublicRoomCard } from '@/features/rooms/components/PublicRoomCard'; import { usePublicRooms } from '@/features/rooms/hooks/useRooms'; import { filterPublicRooms } from '@/features/rooms/utils/publicRooms'; import { useNetworkStatus } from '@/hooks/useNetworkStatus';

export default function PublicRooms() {
  const query = usePublicRooms(publicAppConfig.propertyId); const { isOffline } = useNetworkStatus(); const { width } = useWindowDimensions();
  const [availableOnly, setAvailableOnly] = useState(true); const [minimum, setMinimum] = useState(''); const [maximum, setMaximum] = useState(''); const [facility, setFacility] = useState('');
  const rooms = useMemo(() => filterPublicRooms(query.data ?? [], { availableOnly, minimum, maximum, facility }), [query.data, availableOnly, minimum, maximum, facility]);
  if (query.isLoading) return <Screen><LoadingState label="Memuat kamar…" /></Screen>;
  if (query.error && !query.data) return <Screen><ErrorState description="Daftar kamar belum dapat dimuat." onRetry={() => void query.refetch()} /></Screen>;
  return <Screen scrollProps={{ refreshControl: <RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} /> }}><OfflineBanner visible={isOffline} /><View style={styles.header}><AppText variant="titleXl">Kamar Manzsa Residence</AppText><AppText tone="secondary">{rooms.length} kamar sesuai filter</AppText></View><Card style={styles.filters}><Button label={availableOnly ? 'Hanya tersedia' : 'Semua status publik'} variant={availableOnly ? 'secondary' : 'outline'} onPress={() => setAvailableOnly((value) => !value)} /><View style={styles.row}><TextField label="Harga minimum" value={minimum} onChangeText={setMinimum} keyboardType="numeric" style={styles.input} /><TextField label="Harga maksimum" value={maximum} onChangeText={setMaximum} keyboardType="numeric" style={styles.input} /></View><TextField label="Fasilitas" value={facility} onChangeText={setFacility} placeholder="Contoh: Wi-Fi" /></Card>{rooms.length ? <View style={styles.grid}>{rooms.map((room) => <View key={room.id} style={[styles.item, width >= 1050 && styles.itemThree]}><PublicRoomCard room={room} /></View>)}</View> : <EmptyState title="Tidak ada kamar yang cocok" description="Ubah filter atau periksa kembali ketersediaan kamar." />}</Screen>;
}
const styles = StyleSheet.create({ header: { gap: spacing[2] }, filters: { gap: spacing[3] }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] }, input: { minWidth: 180, flex: 1 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[4] }, item: { width: '100%', minWidth: 280 }, itemThree: { width: '31%', flexGrow: 1 } });
