"use client";
import{useForm}from"react-hook-form";import{zodResolver}from"@hookform/resolvers/zod";import{z}from"zod";import{useState}from"react";import{useRouter}from"next/navigation";import{CloudinaryUploader}from"@/components/cloudinary-uploader";import type{MediaAsset}from"@/types/domain";
const schema=z.object({name:z.string().min(3),description:z.string().min(10),address:z.string().min(5),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),whatsapp:z.string().min(8),email:z.string().email(),operatingHours:z.string().min(3),houseRules:z.string(),bankName:z.string(),bankAccount:z.string(),bankHolder:z.string(),bookingExpirationMinutes:z.number().int().min(10).max(10080),cancellationPolicy:z.string(),invoiceInformation:z.string(),seoTitle:z.string().min(3).max(70),seoDescription:z.string().min(10).max(160)});type Values=z.infer<typeof schema>;
export function SettingsForm({settings}:{settings:Record<string,unknown>}){
 const router=useRouter(),[logo,setLogo]=useState<MediaAsset[]>(settings.logo?[settings.logo as MediaAsset]:[]),[og,setOg]=useState<MediaAsset[]>(settings.openGraphImage?[settings.openGraphImage as MediaAsset]:[]),[message,setMessage]=useState("");const bank=settings.bank as Record<string,string>|undefined,coordinates=settings.coordinates as Record<string,number>|undefined;
 const{register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{name:String(settings.name||"Manzsa Residence"),description:String(settings.description||""),address:String(settings.address||""),latitude:coordinates?.latitude||0,longitude:coordinates?.longitude||0,whatsapp:String(settings.whatsapp||""),email:String(settings.email||""),operatingHours:String(settings.operatingHours||""),houseRules:String(settings.houseRules||""),bankName:bank?.name||"",bankAccount:bank?.accountNumber||"",bankHolder:bank?.holder||"",bookingExpirationMinutes:Number(settings.bookingExpirationMinutes||30),cancellationPolicy:String(settings.cancellationPolicy||""),invoiceInformation:String(settings.invoiceInformation||""),seoTitle:String(settings.seoTitle||"Manzsa Residence"),seoDescription:String(settings.seoDescription||"")}});
 async function submit(v:Values){const res=await fetch("/api/owner/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...v,coordinates:{latitude:v.latitude,longitude:v.longitude},bank:{name:v.bankName,accountNumber:v.bankAccount,holder:v.bankHolder},logo:logo[0]||null,openGraphImage:og[0]||null})}),data=await res.json();setMessage(res.ok?"Pengaturan berhasil disimpan.":data.message||"Pengaturan gagal disimpan.");if(res.ok)router.refresh()}
 const textFields:Array<[keyof Values,string]>=[["name","Nama properti"],["address","Alamat"],["whatsapp","WhatsApp"],["email","Email"],["operatingHours","Jam operasional"],["bankName","Nama bank"],["bankAccount","Nomor rekening"],["bankHolder","Nama pemilik rekening"],["seoTitle","SEO title"]],numberFields:Array<["latitude"|"longitude"|"bookingExpirationMinutes",string]>=[["latitude","Latitude"],["longitude","Longitude"],["bookingExpirationMinutes","Kedaluwarsa booking (menit)"]];
 return <form className="card form" onSubmit={handleSubmit(submit)}><div className="grid three">{textFields.map(([n,l])=><div className="field" key={n}><label>{l}</label><input className="input" {...register(n)}/>{errors[n]&&<span className="field-error">{String(errors[n]?.message)}</span>}</div>)}{numberFields.map(([n,l])=><div className="field" key={n}><label>{l}</label><input className="input" type="number" step={n==="bookingExpirationMinutes"?1:"any"}{...register(n,{valueAsNumber:true})}/>{errors[n]&&<span className="field-error">{errors[n]?.message}</span>}</div>)}</div>{([["description","Deskripsi"],["houseRules","Aturan kos"],["cancellationPolicy","Kebijakan pembatalan"],["invoiceInformation","Informasi invoice"],["seoDescription","SEO description"]]as Array<[keyof Values,string]>).map(([n,l])=><div className="field" key={n}><label>{l}</label><textarea className="input" rows={3}{...register(n)}/></div>)}<CloudinaryUploader purpose="property" resourceId="logo" value={logo} onChange={setLogo} multiple={false}/><CloudinaryUploader purpose="property" resourceId="open-graph" value={og} onChange={setOg} multiple={false}/>{message&&<div className={message.includes("berhasil")?"alert success":"alert"}>{message}</div>}<button className="button dark" disabled={isSubmitting}>{isSubmitting?"Menyimpan…":"Simpan pengaturan"}</button></form>
}
