(()=>{
 const compact=document.createElement('style');
 compact.textContent=`@media(min-width:1024px){body{font-size:13px}.layout{grid-template-columns:200px 1fr}.sidebar{width:200px;padding:18px 13px}.brand{font-size:15px;padding:8px 8px 19px}.tenant-card{padding:11px;margin-bottom:16px;border-radius:13px}.avatar{width:34px;height:34px}.menu{gap:4px}.menu a{padding:9px 10px;border-radius:10px;font-size:11px}.content{padding:0 24px 40px}.topbar{height:58px}.page{max-width:1220px}.head{margin:11px 0 21px}.head h1{font-size:26px}.grid{gap:13px}.card{padding:16px;border-radius:16px}.widget{min-height:124px}.label{font-size:10px;margin-bottom:10px}.value{font-size:20px;margin-bottom:6px}.sub{font-size:11px}.toolbar{gap:8px;margin-bottom:13px}.input,.select,.textarea{border-radius:10px;padding:9px 10px}.btn{padding:9px 14px}.table-wrap{border-radius:16px}th,td{padding:12px 14px;font-size:11px}th{font-size:9px}.state{border-radius:16px;padding:52px 16px}.modal{padding:21px}.modal-head{margin-bottom:18px}.detail-list{gap:10px}.detail-row{padding-bottom:10px;font-size:11px}.field{gap:5px}.field label{font-size:10px}.form{gap:11px}.alert{padding:10px 12px}.invoice{padding:27px;border-radius:16px}.invoice-head{padding-bottom:18px;margin-bottom:18px}.invoice-total{padding:16px;font-size:16px}.demo{right:13px;bottom:13px;padding:6px}.demo button{padding:6px 9px;font-size:9px}}@media(min-width:761px) and (max-width:1023px){.layout{grid-template-columns:225px 1fr}.sidebar{width:225px}.content{padding:0 22px 42px}.topbar{height:64px}.card{padding:18px}.grid{gap:14px}}@media(max-width:760px){body{font-size:14px}.sidebar{width:min(80vw,250px)}.content{padding:0 14px 34px}.topbar{height:58px}.head h1{font-size:25px}.card{padding:16px}.grid{gap:13px}.btn{min-height:42px}.input,.select,.textarea{min-height:44px}.demo{left:8px;right:8px;bottom:8px}}`;
 document.head.appendChild(compact);
 const typography=document.createElement('style');typography.textContent="body,button,input,select,textarea{font-family:'Montserrat',sans-serif}h1,h2,h3,h4,h5,h6{font-family:'Cormorant Garamond',serif}";document.head.appendChild(typography);
 const landingTheme=document.createElement('style');landingTheme.textContent=".tenant-hero{background:linear-gradient(135deg,#1da1f2,#1269a4);color:#fff;border-radius:18px;padding:21px;margin:10px 0 20px}.tenant-hero .head{margin:0}.tenant-hero .head p{color:#ffffffc7}.tenant-hero .head h1{font-size:30px}.widget:nth-child(3n+1){border-top:3px solid #1da1f2}.widget:nth-child(3n+2){border-top:3px solid #c6f564}.widget:nth-child(3n){border-top:3px solid #111827}@media(max-width:760px){.tenant-hero{padding:17px}.tenant-hero .head h1{font-size:26px}}";document.head.appendChild(landingTheme);
 const compactWidth=document.createElement('style');compactWidth.textContent='@media(min-width:1024px){.page{max-width:976px!important}}';document.head.appendChild(compactWidth);
 const page=document.body.dataset.page||'dashboard';
 const links=[['dashboard','Ringkasan','index.html'],['booking','Booking Saya','booking.html'],['tagihan','Tagihan & Pembayaran','tagihan.html'],['keluhan','Keluhan','keluhan.html'],['pengumuman','Pengumuman','pengumuman.html'],['aktivitas','Aktivitas','aktivitas.html'],['profil','Profil','profil.html']];
 document.querySelector('[data-shell]').innerHTML=`<div class="layout"><aside class="sidebar" data-sidebar><a class="brand" href="../aeline_landing_page.html">⌂ Manzsa Residence</a><div class="tenant-card"><div class="avatar">AR</div><div><p>Aulia Rahman</p><small>Tenant · Kamar 201</small></div></div><nav class="menu">${links.map(x=>`<a class="${page===x[0]?'active':''}" href="${x[2]}">${x[1]}</a>`).join('')}</nav><div class="sidebar-bottom menu"><a href="../aeline_landing_page.html">Kembali ke Website</a><a href="../login.html">Keluar</a></div></aside><div class="content"><header class="topbar"><button class="mobile-menu" data-sidebar-toggle>☰</button><div></div><div style="font-size:13px"><strong>Aulia Rahman</strong></div></header><main class="page" data-page-content></main></div></div><div class="demo"><button data-demo="normal" class="active">Normal</button><button data-demo="loading">Loading</button><button data-demo="empty">Empty</button><button data-demo="error">Error</button></div>`;
 document.querySelector('[data-sidebar-toggle]').onclick=()=>document.querySelector('[data-sidebar]').classList.toggle('open');
 window.T={page,state:'normal',money:n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n),content:document.querySelector('[data-page-content]'),setState(s){this.state=s;document.querySelectorAll('[data-demo]').forEach(b=>b.classList.toggle('active',b.dataset.demo===s));window.renderTenant?.()},head:(title,desc,action='')=>`<div class="tenant-hero"><div class="head"><div><h1>${title}</h1><p>${desc}</p></div>${action}</div></div>`,loading:(count=4)=>`<div class="grid g${Math.min(count,4)}">${Array.from({length:count},()=>`<div class="card"><div class="skeleton"></div><div class="skeleton big"></div><div class="skeleton"></div></div>`).join('')}</div>`,stateBox:(title,text,retry=true)=>`<div class="state"><h3>${title}</h3><p>${text}</p>${retry?'<button class="btn btn-dark" onclick="T.setState(\'normal\')">Coba Lagi</button>':''}</div>`};
 document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>T.setState(b.dataset.demo));
})();
