(()=>{
 const responsiveFix=document.createElement('style');
 responsiveFix.textContent=`.site-header{position:fixed!important;z-index:100!important;top:0;left:0;right:0}.field input[type=checkbox]{width:auto!important;min-height:0!important;margin-right:6px}.field label:has(input[type=checkbox]){display:flex;align-items:flex-start}@media(min-width:1024px){body{padding-top:68px!important;font-size:13px}.nav{height:68px!important}.brand{font-size:18px}.links{gap:22px;font-size:10px}.nav-actions{gap:11px}.btn{padding:10px 18px}.hero{padding:56px 0!important}.section{padding:51px 0!important}.shell{padding-left:20px!important;padding-right:20px!important}.title{font-size:clamp(34px,4vw,54px);margin-bottom:18px}.lead{font-size:15px}.section-title{font-size:clamp(26px,3.2vw,39px)}.grid{gap:16px!important}.card{padding:22px!important;border-radius:19px}.icon{width:37px;height:37px;border-radius:11px;margin-bottom:18px}.form{gap:14px}.field input,.field textarea,.field select,.search{padding:10px 12px;border-radius:11px}.auth-wrap{min-height:calc(100dvh - 68px)}.auth-side{padding:58px}.auth-panel{padding:48px}.auth-box{max-width:400px}.site-footer{padding:38px 0}.mobile-nav{top:68px}}@media(min-width:701px) and (max-width:1023px){body{padding-top:76px!important}.nav{height:76px!important}.hero{padding:63px 0!important}.section{padding:58px 0!important}.card{padding:20px!important}.grid{gap:15px!important}}@media(max-width:1180px){.links,.nav-actions{display:none!important}.mobile-toggle{display:block!important}}@media(max-width:700px){body{padding-top:64px!important}.nav{height:64px!important}.auth-wrap{display:block!important;min-height:calc(100dvh - 64px)}.auth-side{display:none!important}.auth-panel{min-height:calc(100dvh - 64px);padding:28px 16px!important;align-items:start!important}.auth-box{width:100%!important;max-width:480px;margin:auto}.auth-box .g2{grid-template-columns:1fr!important}.auth-box .section-title{font-size:30px!important}.form{gap:12px!important}.field input,.field select{min-height:44px}.field input[type=checkbox]{min-height:0!important}.mobile-nav{position:absolute;top:58px;left:0;right:0;margin:0 12px!important;max-height:calc(100vh - 76px);overflow:auto;box-shadow:0 18px 44px #0003}}`;
 document.head.appendChild(responsiveFix);
 const typography=document.createElement('style');typography.textContent="body,button,input,select,textarea{font-family:'Montserrat',sans-serif}h1,h2,h3,h4,h5,h6{font-family:'Cormorant Garamond',serif}";document.head.appendChild(typography);
 const compactWidth=document.createElement('style');compactWidth.textContent='@media(min-width:1024px){.shell{max-width:1024px!important}.photo{height:192px!important;border-radius:16px!important}.map{min-height:304px!important;border-radius:19px!important}.empty{padding:48px 19px!important;border-radius:19px!important}.accordion button{padding:16px 0!important}.accordion-content{padding-bottom:16px!important}.lightbox button{width:37px!important;height:37px!important;font-size:18px!important}}';document.head.appendChild(compactWidth);
 const page=document.body.dataset.page||'';
 const header=document.querySelector('[data-site-header]');
 if(header)header.innerHTML=`<header class="site-header"><nav class="shell nav"><a class="brand" href="aeline_landing_page.html#beranda" aria-label="Manzsa Residence"><svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 22V12h6v10"/></svg>Manzsa Residence</a><div class="links"><a href="aeline_landing_page.html#beranda">Beranda</a><a href="aeline_landing_page.html#tentang">Tentang</a><a href="aeline_landing_page.html#kamar">Kamar</a><a href="aeline_landing_page.html#fasilitas">Fasilitas</a><a href="aeline_landing_page.html#galeri">Galeri</a><a href="aeline_landing_page.html#faq">FAQ</a><a href="aeline_landing_page.html#kontak">Kontak</a></div><div class="nav-actions"><a href="login.html">Login</a><a class="btn btn-lime" href="registrasi.html">Daftar</a></div><button class="mobile-toggle" data-nav-toggle aria-label="Buka menu" aria-expanded="false">☰</button></nav><div class="mobile-nav" data-mobile-nav><a href="aeline_landing_page.html#beranda">Beranda</a><a href="aeline_landing_page.html#tentang">Tentang</a><a href="aeline_landing_page.html#kamar">Kamar</a><a href="aeline_landing_page.html#fasilitas">Fasilitas</a><a href="aeline_landing_page.html#galeri">Galeri</a><a href="aeline_landing_page.html#faq">FAQ</a><a href="aeline_landing_page.html#kontak">Kontak</a><a href="login.html">Login</a><a href="registrasi.html">Daftar</a></div></header>`;
 const footer=document.querySelector('[data-site-footer]');
 if(footer)footer.innerHTML=`<footer class="site-footer"><div class="shell footer-grid"><div><div class="brand">⌂ Manzsa Residence</div><p style="color:#9ca3af;max-width:380px">Hunian nyaman dengan proses sewa yang jelas dan praktis.</p></div><div><strong>Navigasi</strong><div class="footer-links"><a href="aeline_landing_page.html#tentang">Tentang</a><a href="aeline_landing_page.html#kamar">Kamar</a><a href="aeline_landing_page.html#fasilitas">Fasilitas</a><a href="aeline_landing_page.html#galeri">Galeri</a></div></div><div><strong>Kontak</strong><div class="footer-links"><span>+62 812-3456-7890</span><span>halo@manzsaresidence.id</span><span>Sen–Sab, 08.00–18.00</span></div></div></div></footer>`;
 document.querySelector('[data-nav-toggle]')?.addEventListener('click',e=>{const menu=document.querySelector('[data-mobile-nav]');menu?.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(menu?.classList.contains('open')))});
 if(header){header.querySelector('.site-header').style.cssText='position:fixed;z-index:100;top:0;left:0;right:0;background:linear-gradient(135deg,#1da1f2,#1269a4);box-shadow:none'}
 window.proto={
  wait:(button,text='Memproses...')=>{button.disabled=true;button.dataset.old=button.innerHTML;button.innerHTML=`<span class="spinner"></span> ${text}`},
  done:button=>{button.disabled=false;button.innerHTML=button.dataset.old||'Kirim'},
  email:value=>/^\S+@\S+\.\S+$/.test(value),
  error:(input,message)=>{const out=input.closest('.field')?.querySelector('.field-error');if(out)out.textContent=message;input.style.borderColor=message?'#dc2626':''}
 };
})();
