import { Link, type Href } from 'expo-router';
import { Image } from 'expo-image';
import { MapPin, ShieldCheck } from 'lucide-react-native';
import { Linking, StyleSheet, useWindowDimensions, View } from 'react-native';
import { EmptyState, ErrorState, LoadingState, OfflineBanner } from '@/components/feedback';
import { AppText, Button, Card, Screen } from '@/components/ui';
import { colors } from '@/design/colors'; import { radii } from '@/design/radii'; import { spacing } from '@/design/spacing';
import { publicAppConfig } from '@/config/public'; import { useNetworkStatus } from '@/hooks/useNetworkStatus';
import { PublicRoomCard } from '@/features/rooms/components/PublicRoomCard'; import { usePublicRooms } from '@/features/rooms/hooks/useRooms';
import { usePublicProperty } from '../hooks/useProperty';

export function PublicHomeContent() {
  const property = usePublicProperty(publicAppConfig.propertyId); const rooms = usePublicRooms(publicAppConfig.propertyId); const { isOffline } = useNetworkStatus(); const { width } = useWindowDimensions();
  if (property.isLoading) return <Screen><LoadingState label="Memuat Manzsa Residence…" /></Screen>;
  if (property.error) return <Screen><ErrorState description="Profil properti belum dapat dimuat." onRetry={() => void property.refetch()} /></Screen>;
  if (!property.data) return <Screen><EmptyState title="Profil properti belum tersedia" description="Dokumen property belum dibuat atau belum dipublikasikan." /></Screen>;
  const data = property.data; const available = (rooms.data ?? []).filter((room) => room.status === 'available').slice(0, 3); const desktop = width >= 900;
  return <Screen><OfflineBanner visible={isOffline} /><View style={[styles.hero, desktop && styles.heroDesktop]}><View style={styles.heroCopy}><AppText variant="caption" tone="brand">SATU PROPERTI • MANZSA RESIDENCE</AppText><AppText variant="displayLg">{data.name}</AppText><AppText variant="bodyLg" tone="secondary">{data.shortDescription}</AppText><View style={styles.actions}><Link href={'/rooms' as Href} asChild><Button label="Lihat kamar tersedia" /></Link><Link href={'/(auth)/login' as Href} asChild><Button label="Login penghuni / owner" variant="outline" /></Link></View></View>{data.heroImageUrl ? <Image source={{ uri: data.heroImageUrl }} accessibilityLabel={`Foto utama ${data.name}`} alt={`Foto utama ${data.name}`} contentFit="cover" cachePolicy="memory-disk" style={styles.heroImage} /> : <View style={[styles.heroImage, styles.heroPlaceholder]}><AppText tone="muted">Foto utama belum tersedia</AppText></View>}</View>
  {data.highlights.length ? <Section title="Keunggulan"><View style={styles.grid}>{data.highlights.map((item) => <Card key={item.id} style={styles.third}><ShieldCheck color={colors.brand[600]} size={24} /><AppText variant="titleSm">{item.title}</AppText><AppText tone="secondary">{item.description}</AppText></Card>)}</View></Section> : null}
  <Section title="Kamar tersedia" action={<Link href={'/rooms' as Href} style={styles.textLink}>Lihat semua</Link>}>{rooms.isLoading ? <LoadingState /> : available.length ? <View style={styles.grid}>{available.map((room) => <View key={room.id} style={styles.third}><PublicRoomCard room={room} /></View>)}</View> : <EmptyState title="Belum ada kamar tersedia" description="Kamar yang tersedia akan muncul di sini setelah dipublikasikan." />}</Section>
  {data.facilities.length ? <Section title="Fasilitas umum"><Card><View style={styles.facilityGrid}>{data.facilities.map((item) => <AppText key={item} tone="secondary">• {item}</AppText>)}</View></Card></Section> : null}
  {data.galleryImageUrls.length ? <Section title="Galeri"><View style={styles.gallery}>{data.galleryImageUrls.slice(0, 6).map((uri, index) => <Image key={uri} source={{ uri }} accessibilityLabel={`Galeri ${data.name} ${index + 1}`} alt={`Galeri ${data.name} ${index + 1}`} contentFit="cover" cachePolicy="memory-disk" style={styles.galleryImage} />)}</View></Section> : null}
  <Section title="Lokasi"><Card><View style={styles.location}><MapPin color={colors.brand[600]} /><View style={styles.grow}><AppText variant="titleSm">{data.locationLabel}</AppText><AppText tone="secondary">{data.address}</AppText></View>{data.mapsUrl ? <Button label="Petunjuk" variant="secondary" onPress={() => void Linking.openURL(data.mapsUrl!)} /> : null}</View></Card></Section>
  {data.faq.length ? <Section title="Pertanyaan umum">{data.faq.map((item) => <Card key={item.id}><AppText variant="titleSm">{item.question}</AppText><AppText tone="secondary">{item.answer}</AppText></Card>)}</Section> : null}
  <Section title="Hubungi Manzsa Residence"><Card><AppText tone="secondary">{data.email ?? 'Kontak email belum tersedia'}</AppText>{data.whatsappNumber ? <Button label="Hubungi via WhatsApp" onPress={() => void Linking.openURL(`https://wa.me/${data.whatsappNumber!.replace(/\D/g, '')}`)} /> : null}</Card></Section>
  </Screen>;
}
function Section({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <View style={styles.section}><View style={styles.sectionHead}><AppText variant="titleLg">{title}</AppText>{action}</View>{children}</View>; }
const styles = StyleSheet.create({ hero: { overflow: 'hidden', borderRadius: radii.xl, backgroundColor: colors.brand[50], padding: spacing[6], gap: spacing[6] }, heroDesktop: { flexDirection: 'row', alignItems: 'center' }, heroCopy: { flex: 1, gap: spacing[4] }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] }, heroImage: { flex: 1, width: '100%', minHeight: 280, borderRadius: radii.xl }, heroPlaceholder: { alignItems: 'center', justifyContent: 'center', backgroundColor: colors.brand[100] }, section: { gap: spacing[4] }, sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[4] }, third: { minWidth: 260, flex: 1 }, facilityGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[4] }, gallery: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] }, galleryImage: { minWidth: 180, flex: 1, height: 180, borderRadius: radii.lg }, location: { flexDirection: 'row', alignItems: 'center', gap: spacing[3] }, grow: { flex: 1, gap: spacing[1] }, textLink: { minHeight: 44, color: colors.brand[700], padding: spacing[2], fontWeight: '700' } });
